image: rambabusaravanan/firebase

stages:
  - deploy

cache:                  
  paths:                
    - node_modules/

deploy:
  stage: deploy
  script:
    - npm install
    - npm run build
    - "firebase use personal-site-17595 --token $FIREBASE_TOKEN"
    - firebase deploy --only hosting -m "Pipe $CI_PIPELINE_ID Build $CI_BUILD_ID" --token "$FIREBASE_TOKEN"
  when: manual